import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { GoogleTagManager } from '@next/third-parties/google';
import Script from 'next/script';
import GoogleScript from './components/GoogleScript';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <Script
          async={true}
          src='https://securepubads.g.doubleclick.net/tag/js/gpt.js'
        />
        {/* <GoogleScript /> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
